#! /bin/bash

# set directory paths
fileNameDir = '/gpfs/gibbs/pi/huckins/girgenti_celltype_models' 

# set desired filename
fileNameWant = 'Excitatory_Neurons'

# make directory for selected files to be stored
mkdir /home/ekw28/AN-CellTypeS-Predixcan/freeze3_cellTypes_repo/$fileNameWant
outpath = /home/ekw28/AN-CellTypeS-Predixcan/freeze3_cellTypes_repo/$fileNameWant



# loop thru files 
for file in '$directory'/*; do 
    # check if filename contains desired element 
    if [['$file' == $fileNameWant]]; then 
    cp '$file' outpath
  fi 
done
